version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: techx-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: techx_todo
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: techx-backend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=1234
      - DB_NAME=techx_todo
      - JWT_SECRET=techx
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "yarn mikro-orm migration:up && yarn mikro-orm seeder:run && yarn start:dev"

volumes:
  db-data:
